###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/623a2c3ffb9ba056daac68eb
###
DELETE http://localhost:3001/api/persons/623a32fba8a24aa10f262b74
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Patricia Sobieska",
    "number": "600-464-176"
}