GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Postman is a good tool for testing a REST-api",
    "important": true
}
###
PUT http://localhost:3001/api/notes/623623cdeaccef0ad2704660
Content-Type: application/json

{
    "content": "REST Client is a good tool for testing a REST-api",
    "important": true
}